### ISSUE TITLE
1. 홈페이지 가입- 인증메일 발송 주소

### ISSUE THREAD

**Issue by mozodev** [ictact-coop/suwonedu-nuguna#1]
회원 가입, 비번 수정 등에 사용할 외부 smtp 서비스를 사용

- [x] 서비스 가입
- [x] 메일 발송 도메인 관련 설정
- [x] 모듈 추가 및 설정

**Comment by mozodev** [comment]
c802d47d1df9554d4980854233bbafb896efd6ce

**Comment by suwonedu** [comment]
메일 주소 변경 확인했습니다.
혹시나 싶은 마음에,  
가입인증 링크 아래에
"이 메일은 발신전용 메일로, 수신이 불가합니다." 라는 문구를 넣었으면 합니다.

**Comment by mozodev** [comment]
반영했습니다. 확인해보시고 더 이상 수정할 내용이 없으면 close 해주세요

**Comment by suwonedu** [comment]
확인했습니다. close 하겠습니다.
