### ISSUE TITLE
12. 저작권 관련 페이지 추가 / 하단수정

### ISSUE THREAD

**Issue by mozodev** [ictact-coop/suwonedu-nuguna#12]
1. 메인화면 하단 바 삽입 후 문구 추가

COPYRIGHT ⓒ By 2011 Suwon Lifelong Learning Center. All Right Reserved. 

2. 메인화면 하단 바+문구의 하단 변경

guide - contact us (about 원고와 통합) - direction - 

http://www.wasuwon.net/
하단 CCL 블록 순으로 구성

3. 저작권보호정책 페이지 추가 (웹진과 동일하되, 내용 수정함)

자료이용 및 저작권
수원시평생학습관 누구나학교 홈페이지(이하 홈페이지)에서 제공하는 모든 자료, 즉 BI(brand identity)·웹문서·첨부파일·DB자료는 저작권법에 의하여 보호받는 저작물로써, 별도의 저작권 표시 또는 출처를 명시한 경우를 제외하고는 원칙적으로 수원시평생학습관에 저작권이 있으며, 이를 무단 복제 및 배포하는 경우에는 저작권법 제136조, 137조, 138조, 139조, 140조, 141조, 142조에 의한 저작재산권 침해죄에 해당함을 유념하시기 바랍니다. 
홈페이지에서 제공하는 자료에 대해 영리를 목적으로 하지 아니하고 교육, 학술 등의 공익을 위한 경우에 한하여 저작권, 정보출처, 정보활용 범위, 게시자 등을 명시하고 사용 가능합니다. 
홈페이지의 콘텐츠를 적법한 절차에 따라 다른 인터넷 사이트 혹은 오프라인 상에서 게재하는 경우에도 단순한 오류 정정 이외의 내용의 무단변경을 금지하며, 이를 위반할 때는 형사처벌을 받을 수 있습니다.

게시물의 저작권 귀속 및 책임
회원이 작성하여 홈페이지에 게재 또는 등록한 게시물에 대한 저작권은 회원 본인에게 있는 것으로 추정되며 게시물이 타인의 저작권을 침해하는 경우 그에 대한 책임은 회원 본인이 부담합니다. 수원시평생학습관은 회원이 서비스에 게재 또는 등록한 게시물에 대한 이용권, 서비스 게재권 등을 갖습니다. 다만, 게시물을 출판·판매 등의 방법으로 이용하는 경우에는 사전에 회원 본인의 동의과정을 거칩니다.

회원 상호간 저작권 귀속 및 책임
저작권자의 명시적 동의 없이 타인의 저작물을 무단으로 이용하는 것은 저작권자의 권리를 침해하는 행위임으로 복제·배포·전송 등의 방법으로 타인의 저작권을 침해하는 게시물을 홈페이지에 게재 또는 등록하여서는 안 됩니다. 
홈페이지에 게재 또는 등록된 회원의 게시물을 제3자가 사용하고자 할 경우에는 반드시 해당 회원의 동의를 얻어야 합니다. 
홈페이지에 회원들이 올린 자료는 회원 상호간 지식공유를 위한 것이므로, 수원시평생학습관은 게시물에 대한 정확성에 대한 보증을 하지 않으며, 회원 상호간의 저작권 관련 침해하는 경우에는 어떠한 책임도 부담하지 않습니다. 
또한 수원시평생학습관은 회원들의 게시물 이용에 따른 동의절차를 중재하거나 개입하지 않습니다.

저작권 정책 개정
저작권 정책은 관련 법률 및 정부지침의 변경 또는 수원시평생학습관 내부의 방침 및 사정에 따라서 수시로 개정될 수 있으며, 변경된 사항은 시행전 홈페이지에 공지합니다.

4. 누구나학교 – 소개 하단문구 추가

누구나학교의 가치와 방향을 함께 하고 싶은 분(개인·기관 등)은 협약을 통해 긴밀한 협업이 가능합니다. 
(누구나학교 사업명 및 BI 무단사용 불가) <- 가로안의 말을 누르면, 저작권보호정책 링크 연결

**Comment by suwonedu** [comment]
1. 미팅때, 1번이 있으면 아예 활용이 불가능한 수준이고, 
2번은 비영리 등의 일부 목적으로 사용 가능한 수준이라고 말씀해주셔서

1번은 안 넣고, 2번~4번만 하기로 했습니다.
1번 삭제 부탁드립니다.

2. cc 마크의 그림과 용어(nc, by, nd 순 같아요)의 순서가 맞는지 확인 부탁드립니다.

**Comment by mozodev** [comment]
cc 이미지는 웹진와에 있는것을 그대로 가져와서 사용한건데.. 나중에 웹진와 것도 수정한 이미지로 교체하겠습니다.
반영 완료

**Comment by suwonedu** [comment]
1. 수정사항 확인했습니다. 
2.미팅때 웹진와와 동일하되, 웹진와에서 로고와 각이름(?)이 잘못 매칭 된것 같다고 말씀드렸었습니다.
수정사항은 확인했습니다. close 부탁드립니다.
