### ISSUE TITLE
14. 학교소식-언론보도 게시물이 standby로 다 변경되어 있음

### ISSUE THREAD

**Issue by suwonedu** [ictact-coop/suwonedu-nuguna#14]
http://nuguna.suwonedu.org/media

수정전까지 정상적인 기능.

수정반영 후 해당 게시물의 이미지/동영상 파일이 형체만 있고 보이지 않음.
게시물을 눌렀을때 좌측상단에 standby라고 되어 있음.
수정요청합니다.

**Comment by mozodev** [comment]
반영 완료

**Comment by suwonedu** [comment]
확인했습니다. close 부탁드립니다.
