### ISSUE TITLE
15. 학교소식 4개 게시판 모두 오정보 입력

### ISSUE THREAD

**Issue by suwonedu** [ictact-coop/suwonedu-nuguna#15]
수정 전에는 "누구나학교는~ 있습니다."라는 내용이 없고, 
바로 게시목록이 떴음.
현재는 4개 게시판 모두 해당 박스가 상단에 있고, 그 밑에 게시목록이 있음.
원래대로 수정요청

**Comment by mozodev** [comment]
반영 완료

**Comment by suwonedu** [comment]
수정확인했습니다. close 부탁드립니다.
