### ISSUE TITLE
17. 누구나학교 비정상적인 페이지뷰수 확인

### ISSUE THREAD

**Issue by suwonedu** [ictact-coop/suwonedu-nuguna#17]
안녕하세요 박선영입니다.

누구나학교 홈페이지 관리자 페이지에서
3/3 토요일 페이지뷰가 유독 많아 
좀 걱정되어 메일드립니다. (메일로 사진 첨부)

혹시 업데이트가 진행되었거나,
보안상의 문제가 있지는 않았는지 궁금합니다 ;-;

답변 부탁드립니다 :) 

------------------------------------------------------------------------------------------
 * 여기에 사진을 첨부하려고 하니깐, 자꾸 
 we don't support that file type, try again~ 이런 식으로 안내 멘트가 나옵니다.
 파일 형식을 png, gif, jpeg로 바꿔가면서 올렸는데도 그러네요;-;
 혹시 방법이 따로 있을까요? 
------------------------------------------------------------------------------------------
3/12 박선영, 통화함  * 특정IP의 접속시도인지 확인 후 공유하기로 함.
  - 하지만 그렇더라도, 이런 시도를 막을 솔루션을 학습관에서 구매하기 어려움(매우 고가)
  - 또한 업체에서 작업하더라도 페이지뷰수가 늘어나진 않음

**Comment by suwonedu** [comment]
* 홍영택님 3월 13일 메일

3월 3일 비정상 트래픽 관련

웹서버 로그 파일을 확인해본 결과 구글봇을 포함한 검색엔진의 접근이 1843회 있었고...
이건 정상 범위라고 보시면 됩니다.

apache.userAgent count 
Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html) 528 
Mozilla/5.0 (compatible; MJ12bot/v1.4.8; http://mj12bot.com/) 520 
Mozilla/5.0 (compatible; Yeti/1.1; +http://naver.me/bot) 487 
Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) 100 
Googlebot-Image/1.0 94 
Mozilla/5.0 (compatible; AhrefsBot/5.2; +http://ahrefs.com/robot/) 61 
Mozilla/5.0 (compatible; DotBot/1.1; http://www.opensiteexplorer.org/dotbot, help@moz.com) 36 
Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.96 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html) 15 
Mozilla/5.0 (Windows NT 10.0; WOW64; rv:57.0) Gecko/20100101 Firefox/57.0 - James BOT - WebCrawler http://cognitiveseo.com/bot.html 1 
Slack-ImgProxy (+https://api.slack.com/robots) 1 
 1843 

211.184.127.235
이 아이피에서 8812회의 요청이 들어왔습니다. 전체 20346회 요청 중 8812회는 43.3%에 해당합니다.
초기 화면 2000번, 회원 가입, 관리자 화면 300번 요청을 한 점으로 보아 비정상 사용자인 듯 합니다.
해당 아이피는 서울에 있는 KT 회선을 사용하는 아이피로 조회가 됩니다.

현재 1월 9일에 배포한 1.9.3 버전으로 업그레이드된 상태이고
https://github.com/xpressengine/xe-core/releases/tag/1.9.3

관리자 화면 하단에 보시면 현재 버전과 최신 버전을 확인하실 수 있습니다.

제가 여행 중이었던 기간에 1.9.6 버전까지 새로운 업데이트가 등록됐습니다.
오늘 확인했고 조만간 테스트를 거쳐서 실서버에 반영하도록 하겠습니다.

보안상의 문제가 있었는지 하는 표현은 굉장히 모호한데요..
웹서버 로그만 봐서는 특이한 문제는 찾지 못했습니다.

회원의 개인정보가 유출되었는지 하는 등의 구체적인 보안 감사는 보안 전문가에게 의뢰하셔야 합니다.
본 유지보수 계약의 범위를 넘어서는 일이라고 할 수 있습니다.

어쨌든 궁금하신 사항에 대한 답이 되었으면 좋겠네요.
전에도 말씀드렸듯이 긴급한 건이 아니면 바로 바로 대응해드리기는 어렵습니다.
긴급한 건이라는 것은 사이트가 정지해서 서비스가 안되는 상태라고 할 수 있습니다.

제가 직접 제작한 웹사이트라면 비교적 신속하게 대응할 수 있지만 다른 사람이 만들었고
인수인계도 제대로 받지 못한 상태에서 이정도면 빠르게 수정해드린 거라고 생각합니다.

회원가입 시 특정 이메일 도메인 차단, 
xe 업그레이드는 다음 주 월요일에 확인하실 수 있게 작업하겠습니다.

**Comment by suwonedu** [comment]
부이사장님 자세한 답변 감사합니다 ^^
제가 홈페이지 보안(?), 운영에 대해 잘 몰라서
페이지뷰수가 과도한 게 무언가 연관된건가 싶어
그렇게 여쭤봤던 겁니다 ^^; 

이번 페이지뷰수와 일회성 이메일 가입 및 활동은 
이후 홈페이지 관리에 있어 문제의 소지가 발생하지 않을까 하는 우려가 있었고요.
메일로는 충분한 설명이 안 될 것 같은데 여행 중이셔서
월요일에 전화 연락드렸었습니다^^

이후에도 누구나학교가 짜잘하게(?) 문의사항들이 많아서 중간중간 연락드리지 않을까 싶긴 합니다.
급한 건과 아닌 건에 대해 좀 더 자세히 말씀드리도록 하겠습니다. 

그리고 추가 질문입니다!
1. 211.184.127.235 아이피의 접속(8812회)은 2018년 3월 12일 월요일 저녁 8~9시 사이에 있었던 게 맞을까요?
(3월 3일 비정상 접속자가 해당 아이피는 아닌거고요? 
그림을 봤을때 그런것 같은데 맞는지 확인차 여쭤봅니다. 
페이지뷰수로 봤을때는 3월 12일-약 800건-은 3월 3일-약 8000건-처럼 많지 않았꺼든요) 
(관리자 접속 시도도 있길래, 혹시 이전 유지보수업체인 아즈측의 ip였을까 싶기도 합니다)

2. 그리고 3월 3일은 그럼 정상 접속이었던 걸까요?

3. 저희가 개인정보 유출여부를 알 수 있는 방법은 무엇일까요?

4. 누구나학교 홈페이지의 현재 보안수준은 어느 정도일까요..? 
4-1. xe 버전과 보안수준은 연관이 있나요?)

 답변 부탁드립니다 :)

**Comment by mozodev** [comment]
1. 3월 3일 비정상 접근 211.184.127.235
2. 당연히 비정상 접근이죠.
3. 명확한 방법은 없고 서버 root 권한이 탈취되었거나 데이터 유출을 시도한 서버 로그를 발견하게 되거나, 
유출한 사람이 익명으로 이 사이트에서 개인정보를 빼왔다고 선언하고 다니면 명시적으로 알 수 있겠네요.
4. xe가 이 홈페이지를 동작시키는 소스 코드입니다. 당연히 큰 연관이 있고요. 
제가 보안 전문가는 아니지만 지금까지 여러 사이트를 운영하며 관리하는 기준에서 
큰 보안 취약점이 있어서 보안이 취약한 상태는 아니라고 생각합니다.

```
[Mon Mar 26 09:50:36.294882 2018] [:error] [pid 4176] [client 211.184.127.235:50034] checkUpdate, referer: http://nuguna.suwonedu.org/index.php?module=admin
[Mon Mar 26 10:24:21.004137 2018] [:error] [pid 4400] [client 112.155.190.102:49563] checkUpdate, referer: http://nuguna.suwonedu.org/
[Mon Mar 26 10:28:32.592261 2018] [:error] [pid 4426] [client 211.184.127.235:50393] checkUpdate, referer: http://nuguna.suwonedu.org/index.php?module=admin
[Mon Mar 26 10:42:16.757602 2018] [:error] [pid 4431] [client 211.184.127.235:50449] checkUpdate, referer: http://nuguna.suwonedu.org/index.php?module=admin
[Mon Mar 26 10:44:01.336129 2018] [:error] [pid 4496] [client 211.184.127.235:50482] checkUpdate, referer: http://nuguna.suwonedu.org/index.php?module=admin&act=dispCommentAdminList
```
211.184.127.235
지금도 서버에 관리자 화면에 접근해있는걸로 로그에 나오고 있네요 아마도 이전 업체일 수 있을 듯 합니다.
아 확인을 해보니 해당 계정은 관리자 권한이 없네요. 5개의 계정이 최고 관리자인데 저와 담당자님을 제외하고 3명이 있습니다. 그 중 하나의 계정인 듯 싶네요...

그리고 사진 첨부 시 오류는 아마도 이 저장소의 콜라보레이터가 아니셔서 발생하는 듯 하여 초대 메일을 보냈습니다.
수락해주시면 이후에는 이미지도 업로드할 수 있을 듯 합니다.
그럼 수고하세요~

**Comment by mozodev** [comment]
@suwonedu 참 이슈 작성하실 때 앞에 번호 다실 필요없어요. ㅎㅎ 그냥 제목 쓰고 저장하면 제목 뒤에 회색으로 이슈번호가 표시됩니다. 그 번호로 이야기하시면 될 듯 싶네요...

**Comment by suwonedu** [comment]
안녕하세요

211.184.127.235
해당 아이피에 대해 확인해해보니깐,
아래의 4개 아이디의 아이피 주소로 나옵니다.

누구나학교(제 아이디), 상담실, 상딤실^^(2개는 학습관 직원), 수원시평생학습관(학습관 공용)

그런데, 저희 시설담당자한테 문의해보니
학습관에서 쓰는 ip주소는 192.168.10.~로 시작하고
저는 192.168.10.15라고 하네요.
(시작_cmd_ipconfig_ipv4 기준)

또한 홍보팀에도 확인해보니,
도메인(?) 관련하여 사용하고 있는 카페24와도 무관하다고 합니다.

혹시몰라서, 3월 3일 토요당직자(조진희 연구원)의 사용빈도도 확인 중입니다만
크게 연관은 없을 것 같습니다.

그렇다면,
 1. 컴퓨터 ip주소가 다 다른데, 누구나학교 홈페이지 관리자에 등록되는 ip주소가 같은 건 왜일까요?
 2. 이 ip주소는 공동체it에서 사용하고 있는 ip와도 무관한걸까요?
 3. 이전업체에 전화해서 물어보면 되는걸까요?
     혹시 이전업체에서 무언가 연결 중지를 하지 않아서 생긴 문제라면,
     그 연결을 끊었을 때 문제가 될 만한 상황이 있을까요? 

4. 그리고 위에 답변 중 
   "서버 root 권한이 탈취되었거나 데이터 유출을 시도한 서버 로그를 발견하게 되었을때"
   개인정보 유출여부를 알 수 있다고 하셨는데,
    현재 2가지 다 기록이 없는 걸까요?

답변 부탁드립니다 ;-;

**Comment by mozodev** [comment]
1. 사무실 공용 아이피인듯 싶습니다. 공용 아이피는 사무실의 공유기 아이피로 공유기에 연결된 모든 컴퓨터들의 공용 아이피는 모두가 동일합니다. 192.168 로 시작하는 아이피는 사설 아이피입니다. 더 자세한 정보는 구글에 공용 아이피, 사설 아이피를 검색해보시면 위키 페이지의 설명을 참고하세요.

2. 무관합니다.

3. 이전업체가 아닙니다.

4. 유선 상으로 안내해드린 것처럼 로그를 살펴봤으나 특이점을 찾지 못했습니다. 못 미더우시면 로그파일을 전달해드릴 수 있으니 다른 분에게 부탁하셔서 확인해보시기 바랍니다.

이상 이 이슈는 닫겠습니다.
