### ISSUE TITLE
18. 일회용 메일로 홈페이지 가입 및 활동

### ISSUE THREAD

**Issue by suwonedu** [ictact-coop/suwonedu-nuguna#18]
안녕하세요 박선영입니다.

누구나학교에 1시간 일회용 메일로 가입을 해서, 
2회 이상 부적절한 게시물(낚시 동영상)을 올린 회원이 있습니다.
현재는 이용을 정지시켜놨습니다.
(아이디 삭제는 선생님과 문제 공유 후 하려고 합니다.)

관련하여 누구나학교 보안 문제는 없는 것인지
(혹 앞서 보내드린 메일 내용과 연관성은 없는지)
앞으로 이러한 스팸관리는 어떻게 해야 할지 
논의하고 싶습니다.

자세한 문제 경과는 아래를 참고해주세요^^
감사합니다. 
------------------------------------------------------------------------------------------
1. 1월 31일 김지우 회원가입
  (포켓몬gooo, vhzptahs77@ruu.kr, 010-4545-1326) 
2. 1월 31일~2월 21일 김지우, 후기게시판에 2차례 낚시동영상 올림
   1) 첫 번째 작성글 확인 후 해당글 삭제.
    회원에게 적절하지 않은 게시물이라 삭제한다는 안내문자 발송함
   2) 2월 21일 두 번째 작성글 확인 후 해당글 삭제,
   회원에게 연락하였으나 통화연결되지 않음. 
   회원에게 적절하지 않은 게시물이라 삭제한다는 안내와
   2월 28일까지(7일동안) 홈페이지 이용 제한된다는 안내를 문자로 발송함
3. 3월 7일 비정상적인 이메일주소로 가입했음을 확인했음
4. 비고 : ruu.kr  1시간 일회용 이메일 

 *https://blog.naver.com/wayfater/221129450079
-------------------------------------------------------------------------------------------

3. 3/12 박선영, 통화함
 * 메일 가입 시, @이하 주소 직접입력 불가하도록 수정 예정
  - 일회성 메일의 종류가 매우 다양하기 때문에 가입을 막는 것은 사실상 불가능함. 현재 확인된 ruu.kr를 막는 것보다 @이하 주소 관리가 현실적인 대안임.
  - 현재까지 가입된 아이디(메일 주소)를 확인하여, 직접입력하지 않고도 원활한 가입이 가능하도록 정리할 예정

**Comment by suwonedu** [comment]
*3월 12일 통화
 
메일 가입 시, @이하 주소 직접입력 불가하도록 수정 예정
  - 일회성 메일의 종류가 매우 다양하기 때문에 가입을 막는 것은 사실상 불가능함. 현재 확인된 ruu.kr를 막는 것보다 @이하 주소 관리가 현실적인 대안임.
  - 현재까지 가입된 아이디(메일 주소)를 확인하여, 직접입력하지 않고도 원활한 가입이 가능하도록 정리할 예정

**Comment by suwonedu** [comment]
총 110개 도메인이 있네요.. 그냥 일단 하나의 도메인만 가입 제한을 하는 방향으로 해야겠네요.
첨부한 csv 파일 엑셀로 열어보시거나 문자가 깨지면 메모장으로 열어보시면 확인할 수 있습니다.

번거로우시겠지만 유선상의 작업 요청은 기록이 남지 않아서,
깃헙에 이슈 작성해주시면 작업하겠습니다.

**Comment by suwonedu** [comment]
네 확인했습니다!
csv 파일에서 비정상적인 메일 주소(특히 오타)를 제거해봐도 64개 내외 되네요^^
ruu.kr 계정 가입 제한으로 부탁드립니다.
그리고 해당 가입자(김지우)는 탈퇴시키겠습니다.
동일한 사례 발생때마다 따로 말씀드리겠습니다 ;-;

**Comment by mozodev** [comment]
실서버에 적용했습니다.

**Comment by suwonedu** [comment]
네, ruu.kr 가입을 시도해봤는데, 인증메일 발송화면으로 넘어가질 않았습니다.

(별도의 안내 없이, 다음 화면으로 안 넘어가는 것으로 종료해도 될까요?
혹은 일회성 메일은 가입이 불가합니다 와 같은 안내멘트가 뜨거나
        이메일 기재란 옆에 안내를 써두는 게 나을까요?

**Comment by mozodev** [comment]
<img width="652" alt="2018-03-27 5 31 01" src="https://user-images.githubusercontent.com/1661950/37955852-a9015014-31e4-11e8-8a63-3dc3e26de910.png">

브라우저 캐시를 지우고 다시 한번 확인해보시면 위와 같은 메시지가 있습니다.

**Comment by suwonedu** [comment]
브라우저 캐시를 지워도

익스플로러에서는 동일하게 아무런 안내창이 안 뜨고,
크롬에서는 올려주신 화면과 동일한 화면이 뜹니다.

익스플로러 버전의 문제일까요?

**Comment by mozodev** [comment]
수정했습니다.

**Comment by suwonedu** [comment]
확인했습니다. 해당 이슈 종료 부탁드립니다.
