### ISSUE TITLE
2. 홈페이지 가입 – 아이디 드롭박스

### ISSUE THREAD

**Issue by mozodev** [ictact-coop/suwonedu-nuguna#2]
http://nuguna-dev.ictact.kr/index.php?mid=register&act=dispMemberSignUpForm

회원 가입 시 오타로 메일 주소를 잘못 입력하는 것을 방지하기 위해 선택 상자로 도메인을 선택할 수 있게 변경

**Comment by suwonedu** [comment]
http://nuguna.suwonedu.org/index.php?mid=register&act=dispMemberSignUpForm

박스 @ 박스 드롭박스 순인데,
박스 @ 드롭박스 (직접입력을 선택했을때만 드롭박스가 박스로 남아 있는) 

형태로 바꿀 수 있나요?

**Comment by mozodev** [comment]
반영 완료

**Comment by suwonedu** [comment]
박스 수정된 거 확인했습니다.

그런데, 박스에 한메일이 있습니다 ;-; 한메일 지워주세요.
그리고 "※다음(daum), 한메일(hanmail) 사용 불가"는 박스 우측에 그대로 있어야 할 것 같습니다.
(직접입력이 남아있는 만큼, 본인이 입력할 수도 있습니다)

**Comment by mozodev** [comment]
※다음(daum), 한메일(hanmail) 사용 불가는 이전 업체가 사용했던 카페24 이메일 발송 서비스가 문제가 있어서 메일이 전달이 안되었던거고, 이번에 변경한 서비스는 한메일도 잘 전달이 되서 삭제했습니다. 이미 한메일로 가입하신 분도 있습니다.

**Comment by suwonedu** [comment]
예 알겠습니다. 수정완료하겠습니다. close 부탁드립니다.
