### ISSUE TITLE
xe 1.9.6 업데이트 적용하기

### ISSUE THREAD

**Issue by mozodev** [ictact-coop/suwonedu-nuguna#20]
https://github.com/xpressengine/xe-core/releases/tag/1.9.6
https://github.com/xpressengine/xe-core/releases/tag/1.9.5
https://github.com/xpressengine/xe-core/releases/tag/1.9.4

**Comment by mozodev** [comment]
실서버에 업데이트 완료됐습니다.

**Comment by suwonedu** [comment]
확인했습니다. 감사합니다.
