### ISSUE TITLE
20. 개인정보처리방침 수정, 페이지 추가(2개), 개인정보제공동의 화면 

### ISSUE THREAD

**Issue by suwonedu** [ictact-coop/suwonedu-nuguna#21]
1. 회원약관, 개인정보취급방침 별도 화면  : 5월 1일부터 적용 요청
 - "저작권보호정책"처럼 별도 화면 제작 요청
 - 위치: 홈페이지 하단(guide 칸을 좁히고, direction 칸을 넓힌 후,
                                     저작권보호정책 옆에 공간을 마련해서 
                                     "회원약관"과 "개인정보취급방침" 넣어주세요)

3. 개인정보 처리방침 변경 : 5월 1일부터 적용 요청
  가) 실제 적용일 : 2018년 5월 1일 (회원 가입시 변경)
  나) 특이사항 : 제일 하단 "부칙 2. (시행일) 아래 방침은 2018년 5월 1일부터 시행됩니다. "에 링크 추가
    (별도 페이지 : 개인정보처리방침 원안 페이지로 연결,
                           이 연결을 위한 별도 페이지 제작)

2. 개인정보 처리방침 변경 팝업 공지  : 4월 1일부터 4월 10일까지 적용 요청
  *메일로 공유(여전히 파일 올리기가 안됩니다)

4. 개인정보 재동의 : 4월 1일부터 적용
  가) 정해진 기간 이후 첫 번째 로그인 시 무조건 동의화면 뜨도록 한다.
     동의한 회원은 다음 로그인시 화면이 뜨지 않는다.
  나) 2018.4.1.~2019.3.31.까지 동의화면 뜨도록 한다.
  * 요청 페이지 예시 : 메일로 공유
  * 사용한 글씨체 : 나눔고딕OTF ExtraBold
  다) 관리자 페이지-회원목록에서 재동의 여부 열을 생성 부탁드립니다.

 질문!
 1. 전체회원에게 재동의 관련 이메일 발송이 가능한가요?
 2. 재동의하지 않은 회원 목록 삭제(관리) 관련하여 좋은 방안이 있다면 알려주세요 ;-;

**Comment by mozodev** [comment]
질문에 대한 답변입니다.

1. 전체회원에게 재동의 관련 이메일 발송이 가능한가요?
웹진 와 담당자께서 대량 메일 발송 방법을 알고 계십니다.
관련해서 전체 회원 데이터는 제가 메일로 전달해드리겠습니다. 전달해드린 회원 목록으로 대량 메일 발송하시면 됩니다.

2. 재동의하지 않은 회원 목록 삭제(관리) 관련하여 좋은 방안이 있다면 알려주세요 ;-;
회원가입한 날로부터 개인정보보유기간 5년이 경과한 회원 중
재동의하지 않는 회원 목록을 확인해서 일일이 삭제합니다.
거꾸로 회원가입한 날을 기준으로 5년을 더하면 회원 탈퇴시킬 날짜를 구할 수 있습니다.

**Comment by suwonedu** [comment]
안녕하세요!

개입정보 제공팝업을 더이상 보지 않기를 누르더라도,
관리자 모드(관리자 화면 아님), 비회원모드, 회원 모드 모두에서 불규칙하게 나타납니다.
 (회원모드에서 만들기 화면을 가린채 안 지우지는 사례 1회-이용자 신고,
  관리자 모드에서 메인화면, 개별 강좌화면, 공지사항 등 게시물에서도 나타남 등)

 확인 및 수정 부탁드립니다.

**Comment by suwonedu** [comment]
4/6 13:30 통화결과 정리

1. 개입정보 제공팝업을 더이상 보지 않기를 누르더라도,
 관리자 모드(관리자 화면 아님), 비회원모드, 회원 모드 모두에서 불규칙하게 나타납니다.
 (회원모드에서 만들기 화면을 가린채 안 지우지는 사례 1회-이용자 신고,
  관리자 모드에서 메인화면, 개별 강좌화면, 공지사항 등 게시물에서도 나타남 등)
 확인 및 수정 부탁드립니다.
 
 ※ 크롬에서는 나타나지 않음.
    익스플로러에서만 나타나는 오류일 수 있음(캐쉬가 남아 있어서).
    캐쉬 삭제 했기 때문에 이후 동일한 문제 발생하지 않을 것 같음.

2. 개인정보 제공 동의 과정
 1) [구현중:~4/6] 관리자페이지-회원목록: 재동의 여부 및 날짜 표시
 2) [예정:4/13] 회원 전체메일 발송   ① 조언필요: noreply 메일 계정 사용은 불가능한가?
  ② 조언필요: 16조 휴먼계정관리(1년 내 미로그인시 삭제) 2018.4.11.~2019.5.10.
             vs 5년 실질 만료일까지 운영(회원1명당 1번만) 2018.4.11.~2022.4.30.
 3) [구현중:~4/6] 재동의 화면 
  ① 조언필요: 변경에 따른 전체회원 일괄 받기 vs 만료2개월전부터 뜨기(일반적 사이트) 
  ② 조언필요: 동의 or 다음에 (다음에 기능이 굳이 있어야 할까?)
  ③ 조언필요: 회원약관도 넣을 필요 있을까?
 4) [예정] 5년만료+재동의 안함(= 미로그인) -> 2018.5.1.부터 담당자가 삭제
  ① 조언필요: 자동삭제기능 추가 가능여부, 혹은 대상자 알림

   ※ 유지보수로 해당 과정 진행 가능함
  2-2)-① 할 수는 있지만, 비즈메일러가 기록이 남아서 결과보고에 더욱 용이함.
          비즈메일러로 진행하기로 함.
  2-2)-② 회원약관 16조에 따라 2018.4.11.~2019.5.10.까지만 운영
  2-3)-① 운영기간을 고려하여 변경에 따른 전체회원 일괄 받기로 진행
  2-3)-② 무조건 동의해야 사용가능하도록 함(‘다음에’ 기능 없음)
  2-3)-③ 개인정보처리 방침만 넣기로 함(회원약관은 변경 없으므로 굳이 재동의 필요x)
  2-4)-① 가능은 함. 단, 2가지 모두 기능추가(개발)이므로 진행하지 않기로 함.

**Comment by mozodev** [comment]
- [x] 배너 수정 (요청기간 4월 9일 ~)
- [x] 재동의 화면 원고 등 최종 반영 
- [x] 로그인 시 재동의 화면으로 이동, 재동의 후에는 초기 화면으로 이동
- [x] 관리 영역 사용자 목록에 20181재동의 날짜 컬럼 추가 

@suwonedu 실서버에 적용했습니다~

**Comment by suwonedu** [comment]
실서버 반영 확인했습니다.
감사합니다.

그리고 개인정보처리방침 관련하여 
의견없었어서 그대로 진행될 예정입니다.
감사합니다.

**Comment by suwonedu** [comment]
모조님 안녕하세요
2017년 3월 31일까지 가입한
누구나학교 홈페이지 전체회원 명단을 받을 수 있을까요?
(이름-이메일주소 순으로 된 엑셀파일)

지난번에 주신 건 이름이 없어서요;-;

4월 13일에 발송해야 해서,
바쁘시겠지만 오늘중으로 메일이나 깃헙에 올려주셨으면 합니다.

감사합니다!

**Comment by mozodev** [comment]
깃헙에 첨부하면 누구나 다운받을 수 있어서 메일로 전달해드렸습니다.

**Comment by mozodev** [comment]
깃헙에 첨부하면 누구나 다운받을 수 있어서 메일로 전달해드렸습니다.
