### ISSUE TITLE
21. 홈페이지 가입 안됨

### ISSUE THREAD

**Issue by suwonedu** [ictact-coop/suwonedu-nuguna#22]
홈페이지 가입이 정상 작동하지 않고 있습니다.

익스플로러에서는 약관동의 화면(동의)-정보입력 후 등록을 눌러도 다음 화면으로 넘어가지 않습니다.
크롬에서는 정상 작동중입니다.

확인 부탁드립니다.

**Comment by mozodev** [comment]
익스플로러로 홈페이지 가입하도록 수정했습니다.

**Comment by suwonedu** [comment]
확인했습니다. close 부탁드립니다.
