### ISSUE TITLE
21.  삭제데이터 복구, 개인정보 처리방침 재동의 관련

### ISSUE THREAD

**Issue by suwonedu** [ictact-coop/suwonedu-nuguna#23]
1) 삭제데이터 복구 가능여부
 2014.10.22 ~ 2016.4.28 중 가입자 회원목록에 복구
 (삭제일 2019년 10월 22일)

2) 해당 페이지 구현 가능여부 
 - 2018년 4월 30일까지의 가입자 중
 -아직까지 개인정보제공 재동의를 하지 않은 회원에게
 -2023년 4월 30일까지 개인정보 처리방침 재동의 화면을 뜰 수 있도록

 구현자체가 가능한지,
 유지보수차원에서 가능한지 궁금합니다. 

 2번이 가능하면 1번은 복구하고,
 2번이 불가능하면 1번은 복구하지 않으려고 합니다.

**Comment by mozodev** [comment]
재동의 화면 출력하는 작업 가능합니다. 다만 아주 간단한 작업은 아니어서 작업 기간은 1주일 정도 걸릴 듯 합니다. 그런데 원칙적으로 개인정보 취급 방침에 동의하지 않은 분들의 개인정보는 파기하는게 맞습니다.

**Comment by mozodev** [comment]
1. 2014.10.22 ~ 2016.4.28 중 가입자 회원목록에 복구
@suwonedu  2019년 10월 22일 삭제한 603 개 기록 복원 완료했습니다.

**Comment by mozodev** [comment]
2번은 #24 이슈로 등록해주셨으니 복원이 문제가 없으면 이 이슈는 닫겠습니다.
