### ISSUE TITLE
23. (~19.12.1) 페이지 추가/ 로그인 시, 개인정보 확인 및 수정, 추가기재 강제 화면 생성  

### ISSUE THREAD

**Issue by suwonedu** [ictact-coop/suwonedu-nuguna#25]
현재) 우측의 정보만 수집하고 있음.
        학습관 이용자 통계 항목 통일을 위해, 성별/생년월일/주소

수정) 모든 회원이 로그인 시
                       수정가능한 상태로
                       기존 개인정보(저 위의 항목들만)를 보여주고
                       성별/생년월일/주소를 추가로 필수 입력하고
                       확인키를 눌러야 이용 가능하도록.

      상단 안내문구 : 원활한 운영을 위해, 내 정보를 확인해주세요!
                           3차 개인정보 처리방침 적용에 따라, 성별/생년월일/주소도 기재해주세요.
                            
 
    ※ 1번 개인정보 취급방침 미동의자에게 조건생성되는 페이지와 동시에 운영 가능할까요?
       가능하다면 1번 후 1-1번가 뜰 수 있으면 좋을 것 같습니다.

**Comment by suwonedu** [comment]
정상 작동 확인했습니다.

*수정요청사항 
예: "수원시 팔달구 우만1동"으로 넣어주세요
-> 넣어주세요만 빼주세요

**Comment by mozodev** [comment]
수정했습니다.
