### ISSUE TITLE
24. (~19.11.1) 수정/ 회원가입_개인정보처리방침 2차 

### ISSUE THREAD

**Issue by suwonedu** [ictact-coop/suwonedu-nuguna#26]
※깃헙#21 중 3

사안1. 
현재) 회원가입 과정 중 게시되어 있는 개인정보 처리방침이       , 2018년 5월 1일부터 적용된 “개인정보 처리방침 2차”이 아닌        “개인정보 처리방침 1차”로 게시되어 있음. 
수정) 2018년 3월 28일 메일로 전송했던 “개인정보 처리방침 2차” 바로 수정 요청       (늦어도 2019.11.1부터는 확인할 수 있도록)

사안2. 
현재) 회원가입 과정 박스 위에는 “개인정보 취급 방침”, 내용에는 “개인정보처리방침”
수정) 박스 위를 “개인정보처리방침”으로 변경

**Comment by mozodev** [comment]
완료했습니다.
