### ISSUE TITLE
25. (~19.11.1 /~19.12.1) 팝업창 운영 후 수정/ 개인정보처리방침 3차 

### ISSUE THREAD

**Issue by suwonedu** [ictact-coop/suwonedu-nuguna#27]
현재) 개인정보 처리방침 세부내용 수정 

요청) ① 개인정보 처리방침 3차 변경 팝업창 : 2019년 11월 1일~11월 10일만 운영            (제작한 배너는 10월 28일 모조님 메일로 전송)
        ② 별다른 의견제시 없을 시, 회원가입페이지와 개인정보처리방침페이지를 
            2019년 12월 1일부로 개인정보 처리방침 3차로 변경 적용            (개인정보 처리방침 3차 파일은 11월 30일까지 모조님 메일로 전송)

**Comment by mozodev** [comment]
팝업창은 내렸습니다. 12월 1일자 배너와 링크 주시면 귀국해서 추가하도록하겠습니다.

**Comment by suwonedu** [comment]
배너는 따로 없고,
3차안 내용은 (별다른 의견이 없어서) 10월 28일 메일로 보내주신 파일 사용해주시면 됩니다 :) 감사합니다!
