### ISSUE TITLE
26. (~19.11.30) 여러건

### ISSUE THREAD

**Issue by suwonedu** [ictact-coop/suwonedu-nuguna#28]
- [x] **1. 관리자 로그인시에만 “관리”가 보이도록 수정**
* 수정 /  관리자 외 “관리” 보이지 않도록
현재) 회원 로그인 후 상단 우측에 “관리”기능이 보임 .         
클릭시 페이지가 연결되지 않고 안내화면으로 이동(oops! 관리자만 접속이 가능합니다
  
        보이는 경로: 메인화면, 메인화면/찾기/전체, 메안화면/찾기/전체/개별강좌, 
                         메인화면/찾기/진행중, 메인화면/찾기/진행중/개별강좌. 총 5곳

- [x] **2. 대상정보 별도 붉게 표기 삭제(개별모임 클릭 후 확인하도록)**
*삭제 /  누구나학교  개별모임 대상 인원 정보 삭제
             (누구나학교 관리자 로그인 시 요청사항 2가지 : 깃헙#19 중 2)
현재)
-관리자가 관리편의를 위해, 관리자에 한해 로그인 후 모임별 대상정보를 보이도록 요청했었음. 
-정회원도 로그인하면 동일한 정보가 붉게 표시됨

- [x] **3. 안내문 수정 OOPS 삭제**
빨간글씨로 “로그인 후 이용 가능합니다”로 변경
현재) 경로: 1 비회원/만들기/만들기 클릭
               2 비회원/상단바 회색부분의 첫번째아이콘(만들기) 클릭 
        1,2 모두 3번과 같은 안내문 뜸(내용 부적절)
현재) 경로: 1 비회원/상단바 회색부분의 두번째아이콘(후기작성) 클릭 
        2번과 같은 안내문 뜸(내용 부적절)

- [x] **4. RSS 클릭시 페이지 이상**
현재) PC에서는 정상 작동하는데, 모바일에서는 RSS 클릭시 위와 같은 페이지가 나옴
수정) 정상 작동하도록 수정 요청

- [x] **5. 이메일주소변경 클릭시 연결화면 부적절**
현재) 내정보/회원정보보기/이메일주소 변경 클릭
      -> 패스워드 입력창 : 입력
      -> 이메일주소 변경이 아닌, “회원정보 조회/수정”으로 연결됨
수정) 정상연결될 수 있도록 수정

**Comment by suwonedu** [comment]
-관리기능: 안 보이게 확인완료
-개별모임 인원정보: 관리자만 보이게 수정 확인완료

*미수정, 수정요청드립니다!
-안내문 수정
-안내문 수정2
-rss 페이지 이상
-이메일 주소 변경 클릭시 연결화면 부적절

**Comment by suwonedu** [comment]
1~3,5 수정완료 확인했습니다.
4. 제 핸드폰에서는 4번이 여전히 정상적으로 보이지 않습니다.
기종은 note8입니다.

**Comment by mozodev** [comment]
https://wordpress.org/support/topic/rss-feed-not-working-164/
아이폰, 안드로이드 웹브라우저에서 RSS 링크를 직접 열 수 있는 기능을 지원 중단했다고 합니다. 
별도의 RSS 앱을 설치해야 열어볼 수 있다고 합니다. 제가 할 수 있는 부분이 없습니다.

**Comment by suwonedu** [comment]
그럼 모바일에서만 rss를 뺄 수 있을까요?
그리고 지금 데스크탑에서도 rss가 오류 화면이 뜨는데 이건 어떻게 해야 할까요? ㅠ.ㅠ

**Comment by mozodev** [comment]
http://nuguna.suwonedu.org/rss
오류가 아니고 xml 이란 문서 형식이기 때문에 화면이 출력되지 않고 문서 원본이 출력되는겁니다.
정상입니다. 사실 요새 쓰시는 분들이 많지는 않아서 빼도 문제는 없을 거 같습니다.

**Comment by suwonedu** [comment]
1. 그럼 모바일에서는 rss 빼는 걸로 부탁드립니다 :)
2. 와는 데스크탑에서 rss로 화면이 보이는데, 누구나학교는 얼마전까지는 동일하게 보였는데, 지금 xml 문서로 보입니다. 데스크탑은 와처럼 보일 수 있게 할 수 있을까요? 어렵다면 마찬가지로 데스크탑 rss도 뺐으면 합니다.

**Comment by suwonedu** [comment]
모바일, 데스크탑 모두 rss 빼는 걸로 하겠습니다. 감사합니다!
