### ISSUE TITLE
27. (~19.12.1) 수정 / 회원가입 시 필수항목 추가

### ISSUE THREAD

**Issue by suwonedu** [ictact-coop/suwonedu-nuguna#29]
현재)  좌측의 정보만 수집 중

수정) 필수항목 추가  

        이름
        닉네임
        성별 : 남, 여 선택 (*형식: 문자수신허용처럼)
        생년월일  (*형식:  연도/월/일자를 선택할 수 있는 박스)
                        
        연락처
        주소(동까지)  (*형식: 이름처럼 네모박스) 
                           ※옆에 예시로 회색글씨
                             “예: 수원시 팔달구 우만1동” 넣어주세요

수정2)  문자수신허용 부분 안내문 수정
          문자로 유용한 소식을 전달받을 수 있습니다.
          -> 미동의시, 개강 및 준비물 안내에 제한이 있습니다.

**Comment by suwonedu** [comment]
23번 이슈와 마찬가지로
"예: 수원시 팔달구 우만1동" 까지만 넣어주세요. - 넣어주세요를 빼주세요~

**Comment by mozodev** [comment]
수정했습니다.
