### ISSUE TITLE
3. 홈페이지 가입 & 관리자기능 회원 정보 정렬

### ISSUE THREAD

**Issue by mozodev** [ictact-coop/suwonedu-nuguna#3]
![2018-02-20 4 45 19](https://user-images.githubusercontent.com/1661950/36412441-9a034d1c-165d-11e8-947f-cce5f02fdad0.png)

- [x] 홈페이지 가입에서 삭제 -   쪽지 수신허용 
- [x] 회원정보에서 삭제 -  만나이,   쪽지 수신 허용
- [x] 가입한 회원들 중 문자수신 동의여부가 표시되지 않는 경우가 많음. 필수 입력사항인 만큼 확인 필요

**Comment by mozodev** [comment]
수정을 할 수 있으나 코어(OS같은거)를 수정해야해서 
향후 보안 업그레이드 적용 시 매번 따로 패치를 해야하는 문제가 있음... 

반드시 명칭이나 순서가 동일해야하는게 아니라면 이대로 두는게 어떨까 싶습니다. 의견 주세요~

**Comment by mozodev** [comment]
순서는 그대로 유지하고 나머지 이슈만 수정

**Comment by suwonedu** [comment]
1. 
http://nuguna.suwonedu.org/index.php?module=admin&act=dispMemberAdminInsert&member_srl=132009

관리자-회원목록-개별회원 정보 클릭
하면 나오는 회원정보에서 "쪽지수신허용"여부는 불필요합니다. 삭제 부탁드립니다.

2.  가입한 회원들 중 문자수신 동의여부가 표시되지 않는 경우가 많음. 필수 입력사항인 만큼 확인 필요
라고 요청드렸는데, 
2/27 가입자 장영희님도 문자수신 동의여부가 표시되지 않습니다. 
회원가입에서 필수값 설정이 되어 있지 않은 건지, 
값 입력 후에도 회원정보에서는 확인이 안되는 건지 궁금합니다.

**Comment by mozodev** [comment]
확인해본 결과 데이터베이스에 동의여부는 Y로 기록되어 있는데 화면에 표시가 안되고 있네요.
이건 좀 더 테스트를 해본 후에 수정하겠습니다.

**Comment by mozodev** [comment]
이제 관리자 회원 목록 화면에 Y / N 으로 문자수신 동의여부를 조회할 수 있습니다.

**Comment by suwonedu** [comment]
확인했습니다. close 부탁드립니다.
