### ISSUE TITLE
28. (~19.11.8) 오류 수정 / 회원가입 오류

### ISSUE THREAD

**Issue by suwonedu** [ictact-coop/suwonedu-nuguna#30]
현재) 기존가입자가 이미 가입된 이메일 주소로 회원가입을 재시도시, 별도의 안내문 없이 약관동의화면으로 이동됨

수정) 아이디 입력시, 중복메일 검사기능 추가 가능여부 확인 요청(개발여부)

**Comment by mozodev** [comment]
<img width="700" alt="스크린샷 2019-11-11 오후 4 43 29" src="https://user-images.githubusercontent.com/1661950/68573728-43174400-04a3-11ea-99cb-b2ae7fe77418.png">

**Comment by suwonedu** [comment]
확인했습니다. 감사합니다
