### ISSUE TITLE
29. 질문 4가지

### ISSUE THREAD

**Issue by suwonedu** [ictact-coop/suwonedu-nuguna#31]
질문1. 댓글관리에서 신청강좌를 알 수 있는 방법 
현재) 댓글관리에서 신청모임 정보를 볼 수 없음(일일이 눌러봐야 어느 모임에  신청했는지 알 수 있음) 
문의) 어느 모임에서 신청한 건지 같이 뜰 수 있을까요? 내용이 너무 많으면, 강좌번호로라도 표기 가능할까요? (수강신청을 할 때 동일 강좌에 신청한 사람도 다 하나하나 눌러봐야 알아서 넘 번거로워요)
       그리고 저 추천 기능은 사용하지 않아서 없어도 됩니다.  

질문2. XE 업데이트 가능여부
문의)현재 xe 1.9.7 사용 중인데 1.11.5까지 나왔다는 걸까요?
       그럼 저희도 업데이트가 가능한걸까요? 가능하면 부탁드립니다.

질문3. 휴지통 비우기 
문의) 휴지통에 있는 452개의 글은 다 봇으로 작성되었던 글 같은데, 휴지통 비우기 실행해도 될까요? 불필요해 보여서요

질문4. 네이버 검색시 
문의) 다음에서는 “누구나학교”라고 검색하면 간략한 정보가 나오는데, 
네이버에서는 “웹수집 정보를 표시할 수 없음”으로 뜹니다. 혹시 네이버도 표시할 수 있는 방법이 있을까요?

**Comment by mozodev** [comment]
질문1. 댓글관리에서 신청강좌를 알 수 있는 방법
관리자 화면 에 신청강좌를 표시하는 컬럼을 추가하면 됩니다. 이건 다른 이슈로 만들어서 작업하겠습니다.

질문2. XE 업데이트 가능여부
가능합니다. 역시 다른 이슈로 만들어서 작업합니다.

질문3. 휴지통 비우기
그냥 삭제하시면 됩니다.

질문4. 네이버 검색시“웹수집 정보를 표시할 수 없음”
robots.txt 파일을 추가해서 모든 검색 엔진 접근을 허용했습니다. 
시간이 지나서 네이버 검색봇이 정보를 수집해가면 좀 더 표시하지 않을까 싶습니다.

**Comment by suwonedu** [comment]
질문1 수정요청드립니다.

**Comment by mozodev** [comment]
관리자 화면 > 댓글관리에서 신청 강좌 표시 #33 여기 별도 이슈로 등록했으니까 이건 닫겠습니다.
