### ISSUE TITLE
XE 업그레이드

### ISSUE THREAD

**Issue by mozodev** [ictact-coop/suwonedu-nuguna#32]
XE 업데이트 - 8개 버전 변경분 패치
https://github.com/xpressengine/xe-core/releases
질문 4가지 #31
```
 1.9.8 / 1.11.0 / 1.11.1 / 1.11.2 / 1.11.3 / 1.11.4 / 1.11.5 / 1.11.6 
```

**Comment by suwonedu** [comment]
xe 업데이트가 완료된걸까요? 
아직 관리자 모드에서는 
Powered by XE. | Your version: 1.9.8 | Latest version: XE Core ver. 1.11.5	
라고 표현되어서요!

**Comment by suwonedu** [comment]
Your version: 1.11.6 | Latest version: XE Core ver. 1.11.5	

업데이트 확인했습니다.
Latest version: XE Core ver이 1.11.5인데 저희가 더 높은건가요??

**Comment by mozodev** [comment]
네 중앙 저장소 오류인거 같은데 현재 출시된 최신 버전은 1.11.6입니다.
https://github.com/xpressengine/xe-core/releases/tag/1.11.6
