### ISSUE TITLE
회원가입약관, 개인정보처리방침 별도 페이지 생성 및 푸터 링크 노출

### ISSUE THREAD

**Issue by mozodev** [ictact-coop/suwonedu-nuguna#34]
현재) 회원가입약관과 개인정보처리방침은 회원가입 시에만 확인할 수 있음.
        저작권보호정책, 이메일무단수집거부와 동일하게 별도 페이지 생성 필요

요청) 저작권보호정책"처럼 2개 각각 별도 화면 제작 요청
        홈페이지 하단 guide 칸을 좁히고, direction 칸을 넓힌 후,
        저작권보호정책 옆에 공간을 마련해서 "회원약관", "개인정보취급방침" 2줄로 링크페이지 생성

**Comment by suwonedu** [comment]
확인했습니다. close 하겠습니다.
