### ISSUE TITLE
푸터 정보 수정

### ISSUE THREAD

**Issue by mozodev** [ictact-coop/suwonedu-nuguna#35]
요청) guide                                                       
        평   일/토요일  9:00~18:00
        일요일/공휴일  휴무

요청) “네이버지도로 보기(새창)”를 글씨색 주황색, 볼드처리  (현재 구분 잘 안됨)

**Comment by mozodev** [comment]
패밀리사이트
현재) 수원시평생학습관, 아카이브와, 도요새책방, 페이스북, 트위터

수정)
- 유지 : 페이스북
- 추가 : 인문사회공유카페 https://cafe.naver.com/suwonlearn
           거북이공방 https://suwonedu2011.blog.me/
           뭐라도학교 http://cafe.daum.net/3rd-Age
- 변경 : 아카이브와 →　웹진 와
- 디자인 변경: family site 좀 더 길게 (학습관 글씨가 줄바뀜)
- 삭제: 도요새 책방, 트위터 

*순서: 수원시평생학습관, 뭐라도학교, 인문사회공유카페, 거북이공방, 웹진 와, 페이스북

*사이트 모두 새창으로 띄우기 설정

**Comment by suwonedu** [comment]
1. 피피티 2번 수정 완료 확인했습니다.

2. 피피티 3번 수정 보완 요청드립니다.
 1) 패밀리사이트 순서 :  수원시평생학습관, 뭐라도학교, 인문사회공유카페, 거북이공방, 웹진 와, 페이스북
 2) 혹시 학습관이 2줄로 되지 않는 선까지만 패밀리사이트 칸을 조금 더 짧게 할 수 있을까요?

**Comment by suwonedu** [comment]
수정완료 확인했습니다. 클로즈 하겠습니다.

**Comment by suwonedu** [comment]
수정완료 확인했습니다. 클로즈 하겠습니다.
