### ISSUE TITLE
개별강좌&게시물 보조키 통일

### ISSUE THREAD

**Issue by mozodev** [ictact-coop/suwonedu-nuguna#36]
## 상단 (슬라이드 4~7)

경로1 
비회원/메인화면/개별강좌
비회원/찾기/진행중/개별강좌 

경로2
비회원, 회원, 관리자 모두/.학교소식/공지사항~언론보도

경로3
비회원/누구나학교/사례

경로4
관리자/찾기/진행중/개별강좌

경로5
관리자/찾기/마감/개별강좌
관리자/누구나학교/사례/개별강좌

경로6
관리자/찾기/준비중/개별강좌

경로7
모바일/비회원,회원,관리자/ 
메인화면/개별강좌
찾기/진행중/개별강좌
누구나학교/사례
학교소식/공지사항~언론보도

관리자/찾기/마감/개별강좌
관리자/찾기/준비중/개별강좌
             

현재)
위의 7가지 모두 보조키가 다름
확대/축소키 정상작동하지 않음

수정)
pc  => 댓글 아이콘, 출력 아이콘
모바일 => 댓글 아이콘

## 하단 (슬라이드 8)

현재) 
경로
비회원, 회원/찾기/진행중/개별강좌
관리자/찾기/진행중/개별강좌
비회원, 회원, 관리자/누구나학교/사례/개별강좌 

수정) 모든 키 삭제

**Comment by suwonedu** [comment]
피피티 4번(슬라이드 7번까지)
 1. 피시버전: 댓글 아이콘, 출력 아이콘만 남기는 걸로 요청드렸는데, 댓글 아이콘만 확인됩니다
                    (경로1~6까지)
   -> 1. (4/13 오후 3시경 통화) : 원래부터 댓글 아이콘만 있는 화면들이 있었음.
                                                   전체적으로 댓글+출력(일부 페이지 기능추가) 가능여부 확인해주시기로 함. 
 2. 모바일버젼 : 메뉴키가 사라져서 경로 확인이 안됩니다.

**Comment by suwonedu** [comment]
피피티 5번(슬라이드 8번)
수정완료 확인했습니다.

**Comment by suwonedu** [comment]
![KakaoTalk_20200413_103639212](https://user-images.githubusercontent.com/36880166/79097045-b9450d00-7d99-11ea-83cd-bd3087c4cf2a.jpg)

**Comment by suwonedu** [comment]
수정완료 확인했습니다. 클로즈 하겠습니다.

**Comment by suwonedu** [comment]
수정완료 확인했습니다. 클로즈 하겠습니다.
