### ISSUE TITLE
삭제 / 추천, 비추천 키 삭제 

### ISSUE THREAD

**Issue by mozodev** [ictact-coop/suwonedu-nuguna#37]
현재) 경로1. 피시/관리자/찾기/마감/개별강좌
                 피시/관리자/누구나학교/사례/개별강좌
       경로2. 모바일/관리자/찾기/마감/개별강좌
               모바일/관리자/누구나학교/사례/개별강좌
      경로3. 피시, 모바일/회원, 관리자/
                검색창에 “누구나”라고 검색 후
                “이미지/동영상(피시,모바일/회원”, 
                “파일(피시,모바일/회원, 관리자)” 
                 일부 하단에 동일 확인

수정) 추천, 비추천키 삭제

**Comment by suwonedu** [comment]
1) 경로2(모바일)와 경로3의 모바일 버젼 확인이 불가합니다
 (메뉴 삭제로 인해)
2) 피시 버전은 수정 확인했습니다

**Comment by suwonedu** [comment]
수정완료 확인했습니다. 클로즈 하겠습니다.

**Comment by suwonedu** [comment]
수정완료 확인했습니다. 클로즈 하겠습니다.
