### ISSUE TITLE
카데고리 삭제

### ISSUE THREAD

**Issue by mozodev** [ictact-coop/suwonedu-nuguna#38]
관리자, 회원, 비회원
모바일

현재) 관리자, 회원, 비회원 모두 경로 동일
      : 만들기, 만들기/안내
        누구나학교, 누구나학교/소개, 누구나학교/사례
        학교소식, 학교소식/공지사항~언론보도

수정) 카테고리 삭제

**Comment by suwonedu** [comment]
모조님 세부 카데고리 삭제를 요청드렸었는데,
전체 메뉴가 삭제된 것 같습니다. 수정 요청드립니다.

**Comment by mozodev** [comment]
그냥 닫으셔도 됩니다.

**Comment by suwonedu** [comment]
수정완료 확인했습니다. 클로즈하겠습니다.

**Comment by suwonedu** [comment]
수정완료 확인했습니다. 클로즈하겠습니다.
