### ISSUE TITLE
모바일 화면 스타일 조정

### ISSUE THREAD

**Issue by mozodev** [ictact-coop/suwonedu-nuguna#39]
## 회원가입 시 작성 편의증진

현재) 비회원의 회원가입시
       좌측과 같이 글씨가 세로로 나열되어 읽기 불편함.

수정) 가로쓰기로 읽기 편리하게 수정
    *질문: 이 경우 
      좌우 드래그가 되는 것과
     글씨 크기가 작아지는 등 모바일크기에 맞춰서 되는 것 
     중 어떤 방향으로 구현되나요?

## 정보-댓글알림 페이지  

현재) 댓글알림 페이지가 가로로 김. 
수정) 화면크기로 가로길이 조절

## 개별강좌 좌우 드래그됨  

현재) 경로1. 관리자/찾기/진행중/개별강좌
                         찾기/마감/개별강좌
                         찾기/전체/개별강좌
        경로2. 회원/찾기/.진행중/개별강좌
                       찾기/전체/개별강좌 
         *이런강좌 예시 : 1236번, 1210번

         전체적인 화면구성은 모바일형인데,
         강사소개나 교육계획안이 있는 경우
         가로로 드래그가 됨 (화면 길이가 달라짐)

수정) 화면크기로 가로길이 조절

## 관리자-대시보드-문서-진행중, 마감

현재)진행중, 마감 모임이 가로로 김
수정) 화면크기로 가로길이 조절하되 전반적으로 1개의 모임이 너무 길지 않도록(모임명의 가로길이는 좀 더 길게, 날짜는 좀 더 짧게)

현재)진행중, 마감 모임의 하단 키들이 겹쳐 있어서 정상 사용 불가
 문서-> 하단번호, 휴지통 기능 등 아이콘 겹쳐 있음
 댓글-> 하단번호가 검색창에 겹쳐 있음.
수정) 정상사용 가능하도록 수정

**Comment by mozodev** [comment]
## 개별강좌 좌우 드래그됨

http://nuguna.suwonedu.org/117261
http://nuguna.suwonedu.org/153418
http://nuguna.suwonedu.org/155366

알려주신 예를 포함 하나 더 찾았는데 이 경우들이 모두 본문에 table 너비를 강제로 지정해서 발행하는 문제입니다.
이건 상세 화면에서 이 너비를 360px 정도로 줄여서 저장해야 해결할 수 있습니다.

**Comment by suwonedu** [comment]
1, 회원가입 시 작성 편의증진
 - 가로쓰기로 수정된 점 확인했습니다.
 - 편의성을 높이기 위해, 몇가지 항목 수정 요청드립니다.
  1) 비밀번호 찾기 질문 밑으로 "답변" 글씨 이동 부탁드립니다 (답변 칸 나란히 정렬)
  2) 닉네임 칸 가로길이를 줄이면 좋겠습니다.
  3) 연락처에서 "연락 가능한 연락처(스마트폰/집전화) 입력"을 입력칸 아래로 내리면 좋갰습니다.
  4) 문자수신 허용 아랫줄에 ----가 있는데  삭제 부탁드립니다.
  5) 매일링 가입에서 "가입시~구독 가능"을 선택칸 아래로 내리면 좋겠습니다.
  6) 강사사진, 강사소개, 강의가능분야의 답변칸 가로길이를 화면에 맞춰서로 줄이면 좋겠습니다.

**Comment by suwonedu** [comment]
피피티 9번(12번 슬라이드) 회원정보 조회 화면
자기소개와 강의기능소재를 한 화면 안에 나올 수 있도록가로길이 조절 부탁드립니다.

**Comment by suwonedu** [comment]
2. 피피티10(11번 슬라이드) 정보-댓글알림 페이지
 한 화면에 들어오는 거 확인했습니다.
 제목(댓글 내용) 부분이 너무 길어지는데, 
 혹시 "읽은 시간" 대신 "확인일" 정도만 나오고
 제목 부분을 좀 더 길게 할 수 있을까요?

**Comment by suwonedu** [comment]
피피티11(10번 슬라이드) 개별강좌 좌우 드래그됨 : 수정하지 않고 
이후 표 사용 시 내용 참고하겠습니다.

**Comment by suwonedu** [comment]
피피티12(11번 슬라이드) 관리자-대시보드-문서-진행중, 마감 : 수정하지 않는 걸로 하겠습니다^^

**Comment by suwonedu** [comment]
피피티13(12번 슬라이드) 관리자-대시보드-문서-아이콘 겹쳐서 사용 불가
: 정상 사용 가능하도록 수정요청드립니다.

**Comment by suwonedu** [comment]
회원가입 시 작성 편의증진(피피티8번, 슬라이드11번) 수정완료 확인했습니다.
 회원정보 조회 화면(피피티9번, 슬라이드12번) 수정완료 확인했습니다.

내정보-댓글알림 페이지(피피티10번, 슬라이드13번)와
관리자-대시보드-문서-아이콘 겹쳐서 사용 불가(피피티13번, 슬라이드16번)은
수정완료 확인했는데, 저희가 생각했던거랑 다르게 변화되었습니다.
사진상의 그림처럼 변경이 가능할까요? 안되면 원래대로로 했으면 합니다.
*현재 수정 상황
![KakaoTalk_20200414_140801644_01](https://user-images.githubusercontent.com/36880166/79188257-7fd3d680-7e59-11ea-86be-d1c7bafd42fa.jpg)

*원하는 수정방향
![KakaoTalk_20200414_140801644](https://user-images.githubusercontent.com/36880166/79188235-7480ab00-7e59-11ea-82b8-7d515d0ca17e.jpg)
