### ISSUE TITLE
4. 내정보 내 불필요한 기능 삭제

### ISSUE THREAD

**Issue by mozodev** [ictact-coop/suwonedu-nuguna#4]
* ‘친구’, ‘스크랩’ 사용 방법 
   (의미 없다면 삭제)

 * 쪽지함 = 댓글 알림?
 그 외에 따로 쪽지를 보낼 수는 없는 건가?

**Comment by suwonedu** [comment]
http://nuguna.suwonedu.org/index.php?mid=lec_all&act=dispMemberInfo

댓글에서 "알림"을 체크하고 글을 쓰면
내정보-쪽지함에 저장됩니다. 

그래서 기존 이름인 "쪽지함"이 아니라, "댓글 알림"으로 이름만 바꾸고,
해당 기능을 두는 걸로 이야기 마무리 되었습니다. 수정 요청합니다.

**Comment by mozodev** [comment]
반영 완료

**Comment by suwonedu** [comment]
확인했습니다. close 부탁드립니다.
