### ISSUE TITLE
누구나학교 관리자 로그인 시 강좌 순서 엉킴

### ISSUE THREAD

**Issue by mozodev** [ictact-coop/suwonedu-nuguna#40]
현재) 여전히 관리자 모드일 때 강좌 순서가 약간씩 엉킴
요청) 엉키지 않도록 점검 요청

**Comment by suwonedu** [comment]
수정완료 확인했습니다. 클로즈하겠습니다.
감사합니다!!!

**Comment by suwonedu** [comment]
수정완료 확인했습니다. 클로즈하겠습니다.
감사합니다!!!
