### ISSUE TITLE
5. 학교소식 게시판 & 내정보 보기

### ISSUE THREAD

**Issue by mozodev** [ictact-coop/suwonedu-nuguna#5]
http://nuguna-dev.ictact.kr/index.php?mid=profile&document_srl=124882&act=dispMemberInfo

* 학교소식 4개 게시판 모두
 - 게시물 중 하나를 선택해서 이동한 상태에서
  ‘내정보’를 누르면 
   원래 전체 화면의 내정보가 아니라,
   부분적이 내정보가 나온다. 

상단 내정보 링크에서 document_srl=124882 부분 삭제

**Comment by suwonedu** [comment]
http://nuguna.suwonedu.org/index.php?mid=postscript&document_srl=126224&act=dispMemberInfo

여전히 부분적으로 내 정보가 나옵니다. 확인 부탁드립니다.

**Comment by mozodev** [comment]
반영 완료

**Comment by suwonedu** [comment]
확인했습니다. close 부탁드립니다.
