### ISSUE TITLE
7. 검색

### ISSUE THREAD

**Issue by mozodev** [ictact-coop/suwonedu-nuguna#7]
* 강좌제목&강좌번호&강사명으로 검색 안 됨. 본문 내용&댓글(엮인글)&사진파일명&태그에 한해서 검색되고 있음. 
-> 강좌제목&강좌번호&강사명으로 검색 가능하도록 수정

참고
https://xetown.com/qna/251247

**Comment by suwonedu** [comment]
수정완료라 검색해봤는데, 여전히 안됩니다.

* 강의제목은 예전보다 검색이 잘 되는 것 같습니다.
* 강의번호와 강사명은 여전히 검색이 안됩니다. 
메인화면에서 검색했을 때 (860, 810, 나하나)
각 문서들(모임들)이 검색되지 않습니다. 

확인 부탁드립니다.

**Comment by suwonedu** [comment]
수정 확인했습니다. close 부탁드립니다.
 
2월 2일 첫번째 수정요청건 완료 확인했습니다.
고생하셨습니다.

**Comment by mozodev** [comment]
주말 잘 보내세요~
